# Generated by Django 3.2.12 on 2022-04-02 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='img',
        ),
        migrations.AddField(
            model_name='post',
            name='src',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
