# Generated by Django 3.2.12 on 2022-04-02 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20220402_1654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='word',
        ),
    ]
