# Generated by Django 3.2.12 on 2022-04-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_rename_text_post_word'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='no',
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
